STRINGS = {
"app.name":"MinecraftRLLab","app.tagline":"Bringe einem Agenten bei, in Minecraft zu überleben, zu bauen und zu erkunden.","app.restart_required":"Öffne die App neu, um Sprach- oder Modusänderungen anzuwenden.",
"common.continue":"Weiter","common.back":"Zurück","common.cancel":"Abbrechen","common.save":"Speichern","common.close":"Schließen","common.start":"Start","common.stop":"Stopp","common.next":"Weiter","common.done":"Fertig",
"nav.dashboard":"Dashboard","nav.server":"Minecraft-Server","nav.goals":"Ziele","nav.manual":"Manuelle Aktionen","nav.observations":"Beobachtungen","nav.history":"Verlauf","nav.models":"Modelle","nav.updates":"Updates","nav.settings":"Einstellungen","nav.learning":"Lernen",
"onboarding.title":"Willkommen bei MinecraftRLLab","onboarding.subtitle":"Wähle aus, wie du Reinforcement Learning entdecken möchtest.","onboarding.language":"Sprache","onboarding.mode":"Erlebnis","onboarding.name":"Wie sollen wir dich nennen?","onboarding.finish":"Loslegen",
"mode.kids.title":"Kids / Erste Schritte","mode.kids.description":"Eine spielerische Oberfläche mit großen Missionen, Sternen und geführten Lektionen.","mode.beginner.title":"Anfänger","mode.beginner.description":"Die volle App mit freundlichen Erklärungen und Tutorials.","mode.research.title":"Forschung","mode.research.description":"Live-Metriken, Modelle und Experiment-Steuerung.","mode.advanced.title":"Fortgeschritten","mode.advanced.description":"Forschungsmodus plus Rohdaten und Debug-Werkzeuge.",
"kids.home":"Start","kids.missions":"Missionen","kids.learn":"Lernen","kids.progress":"Mein Fortschritt","kids.server":"Server","kids.hello":"Hallo {name}! 👋","kids.ready":"Bereit, deinem Minecraft-Agenten etwas beizubringen?","kids.pick_mission":"Wähle eine Mission","kids.big_start":"▶ Agenten trainieren","kids.big_stop":"■ Training stoppen",
"kids.connected":"Minecraft ist verbunden!","kids.not_connected":"Verbinde zuerst Minecraft","kids.reward":"Belohnung","kids.stars":"Sterne","kids.episode":"Folge {number}","kids.demo_badge":"DEMO","kids.demo_start":"Demo-Lektion ausprobieren","kids.real_start":"In Minecraft trainieren","kids.tip":"Tipp: Der Agent lernt, indem er Dinge ausprobiert und Belohnungen sammelt.",
"goal.diamond.title":"Diamant finden","goal.diamond.description":"Einen echten Diamanten abbauen und besitzen.","goal.portal.title":"Netherportal bauen","goal.portal.description":"Ein Portal bauen und aktivieren.","goal.sword.title":"Holzschwert craften","goal.sword.description":"Holz sammeln und ein Schwert herstellen.","goal.zombie.title":"Zombie besiegen","goal.zombie.description":"Einen Zombie finden und besiegen.",
"kids.goal.diamond.title":"Finde einen glänzenden Diamanten 💎","kids.goal.diamond.description":"Kann dein Agent unter der Erde suchen und einen Diamanten mitbringen?","kids.goal.portal.title":"Öffne ein lila Portal 🟪","kids.goal.portal.description":"Hilf dem Agenten, eine funktionierende Tür in den Nether zu bauen.","kids.goal.sword.title":"Baue ein Holzschwert 🗡️","kids.goal.sword.description":"Starte mit Holz und lerne die Schritte für ein Schwert.","kids.goal.zombie.title":"Besiege einen Zombie 🧟","kids.goal.zombie.description":"Bringe dem Agenten bei, einen Zombie zu finden und den Kampf zu gewinnen.",
"learning.title":"Lernzentrum","learning.subtitle":"Interaktive Lektionen erklären, was der Agent gerade macht.","learning.completed":"Abgeschlossen","learning.steps":"{done}/{total} Schritte","learning.try_demo":"Im Demo-Modus testen","learning.glossary":"RL-Lexikon","learning.achievements":"Erfolge","learning.experiments":"Experiment-Labor",
"tutorial.agent.title":"Was ist ein Agent?","tutorial.agent.description":"Lerne den Spieler kennen, der in Minecraft Entscheidungen trifft.","tutorial.rewards.title":"Ziele & Belohnungen","tutorial.rewards.description":"Sieh, wie Punkte dem Agenten zeigen, was geholfen hat.","tutorial.first_training.title":"Dein erstes Training","tutorial.first_training.description":"Verbinde Minecraft, wähle ein Ziel und spiele eine Episode.","tutorial.graph.title":"Belohnungsgraph lesen","tutorial.graph.description":"Verstehe, was steigende und fallende Rewards bedeuten können.","tutorial.exploration.title":"Erkunden oder ausnutzen?","tutorial.exploration.description":"Warum Epsilon den Agenten manchmal etwas Neues ausprobieren lässt.","tutorial.experiment.title":"Dein erstes Experiment","tutorial.experiment.description":"Vergleiche zwei Trainings-Einstellungen wie ein Forscher.",
"tutorial.step.choose_goal":"Wähle die Mission Holzschwert.","tutorial.step.connect":"Verbinde die App mit deinem Paper-Server.","tutorial.step.start":"Starte eine Trainings-Episode.","tutorial.step.watch_reward":"Beobachte mindestens eine Belohnung des Agenten.","tutorial.step.finish_episode":"Beende die Episode und schau dir das Ergebnis an.",
"glossary.agent.term":"Agent","glossary.agent.explanation":"Der Entscheider, der Minecraft beobachtet und Aktionen auswählt.","glossary.agent.kids":"Der kleine Minecraft-Lerner, dem du etwas beibringst.","glossary.reward.term":"Belohnung","glossary.reward.explanation":"Ein Zahlenwert, der dem Agenten sagt, ob ein Ergebnis hilfreich war.","glossary.reward.kids":"Punkte, die sagen: Das hat geholfen! Oder: Probier etwas anderes!","glossary.epsilon.term":"Epsilon","glossary.epsilon.explanation":"Die Wahrscheinlichkeit, dass der Agent zufällig erkundet statt seine aktuell beste Aktion zu wählen.","glossary.epsilon.kids":"Ein Neugier-Regler: Wie oft soll ich etwas Neues probieren?","glossary.episode.term":"Episode","glossary.episode.explanation":"Ein Trainingsversuch vom Reset bis Erfolg, Misserfolg oder Zeitlimit.","glossary.episode.kids":"Ein kompletter Versuch für die Mission.",
"achievement.first_tutorial":"Erste Schritte","achievement.first_episode":"Erste Episode","achievement.first_success":"Es hat gelernt!","achievement.diamond_mind":"Diamant-Hirn","achievement.portal_master":"Portal-Meister","achievement.zombie_hunter":"Zombie-Jäger","achievement.model_keeper":"Modell-Sammler","achievement.scientist":"Junger Forscher",
"settings.language":"Sprache","settings.experience_mode":"Erlebnis-Modus","settings.kid_name":"Anzeigename","settings.update_channel":"Standard-Updatekanal","settings.auto_updates":"Beim Start nach Updates suchen","settings.repository":"GitHub-Repository","settings.saved":"Einstellungen gespeichert",
"server.title":"Minecraft-Server","server.host":"Host","server.port":"Port","server.player":"Spieler","server.token":"Token","server.connect":"Verbinden","server.install_plugin":"Plugin installieren / aktualisieren","server.choose_folder":"Paper-Serverordner","server.plugin_installed":"Plugin installiert: {path}",
"status.connected":"Verbunden","status.connecting":"Verbinden…","status.error":"Fehler","status.training":"Training","status.idle":"Bereit",
"research.dashboard.title":"Training-Dashboard","research.dashboard.subtitle":"Live-Reinforcement-Learning-Daten aus Minecraft","research.goals.title":"Trainingsziel","research.goals.subtitle":"Wähle Aufgabe und Curriculum-Profil","research.learning.title":"Lernzentrum","research.learning.subtitle":"Tutorials, Lexikon und Experimente neben den Forschungswerkzeugen.",
}
STRINGS.update({
"connection.subtitle":"Verbinde einen Spieler oder installiere das mitgelieferte Paper-Plugin","connection.server_setup":"SERVER-EINRICHTUNG","connection.browse":"Durchsuchen","connection.install_hint":"Das mitgelieferte Plugin wird in den plugins/-Ordner des Servers kopiert.","connection.disconnected":"Nicht verbunden",
"dashboard.episode":"Episode","dashboard.reward":"Belohnung","dashboard.epsilon":"Epsilon","dashboard.loss":"Loss","dashboard.success_rate":"Erfolgsrate","dashboard.best_reward":"Beste Belohnung","dashboard.chart":"EPISODEN-BELOHNUNG","dashboard.episodes":"Episoden","dashboard.offset":"Offset","dashboard.last_action":"Aktion: {action}","dashboard.start":"▶  Training starten","dashboard.stop":"■  Stoppen",
"goals.profile":"Profil","goals.curriculum_note":"CURRICULUM gibt zielabhängige Startgegenstände, damit Lernen schneller überprüft werden kann. Der Erfolg wird weiterhin aus dem echten Minecraft-Zustand geprüft.",
"manual.title":"Manuelle Umgebungssteuerung","manual.subtitle":"Untersuche den Aktionsraum vor oder zwischen Trainingsläufen","manual.action":"AKTION","manual.execute":"Einen Schritt ausführen","manual.connect_hint":"Verbinde einen Server, um den Aktionsraum zu laden.","manual.actions_count":"Das Plugin meldet {count} Aktionen.",
"observation.title":"Beobachtungs-Inspektor","observation.subtitle":"Roher Umgebungszustand vom Paper-Plugin","observation.position":"Position","observation.health":"Leben","observation.food":"Hunger","observation.dimension":"Dimension","observation.zombies":"Zombies in der Nähe","observation.target":"Ziel",
"history.title":"Episoden-Verlauf","history.subtitle":"Abgeschlossene Episoden dieser Sitzung","history.episode":"Episode","history.steps":"Schritte","history.reward":"Belohnung","history.success":"Erfolg","history.reason":"Grund","history.yes":"JA","history.no":"NEIN",
"models.title":"Modell-Checkpoints","models.subtitle":"PyTorch-DQN-Checkpoints speichern und laden","models.none":"Noch kein Modell geladen.","models.save":"Checkpoint speichern","models.load":"Checkpoint laden",
"updates.title":"Builds & Updates","updates.subtitle":"Verifizierte Releases und frisch gebaute Nightlies von GitHub","updates.channel":"Kanal","updates.check":"GitHub prüfen","updates.not_checked":"Noch nicht geprüft","updates.placeholder":"Build-Informationen erscheinen hier.",
})
STRINGS.update({
"tutorial.agent.observe":"Zuerst bekommt der Agent eine Beobachtung: Leben, Inventar, Blöcke in der Nähe, Ziele und weiteren Minecraft-Zustand.","tutorial.agent.action":"Dann wählt er eine Aktion, zum Beispiel laufen, schauen, abbauen, craften oder angreifen.","tutorial.agent.learn":"Nach Belohnung und nächster Beobachtung kann der Lernalgorithmus hilfreiche Aktionen in Zukunft wahrscheinlicher machen.",
"tutorial.rewards.points":"Belohnungen sind Zahlen. Positive Werte fördern Fortschritt; das echte Endziel bekommt das stärkste positive Signal.","tutorial.rewards.negative":"Kleine negative Belohnungen können unnötige Schritte, Schaden oder Bewegungen weg vom Ziel unattraktiver machen.","tutorial.rewards.shaping":"Reward Shaping gibt Zwischenhinweise. Es soll Lernen helfen, ohne so zu tun, als wäre das echte Ziel schon geschafft.",
"tutorial.graph.trend":"Eine steigende durchschnittliche Belohnung kann auf eine bessere Strategie hindeuten, aber eine glückliche Episode reicht nicht als Beweis.","tutorial.graph.noise":"RL-Kurven sind unruhig, weil Minecraft-Situationen und zufällige Erkundungsaktionen zwischen Episoden variieren.","tutorial.graph.compare":"Vergleiche viele Episoden oder mehrere Trainingsläufe statt nur einen Punkt im Graphen.",
"tutorial.exploration.explore":"Exploration bedeutet, Aktionen auszuprobieren, die momentan nicht als beste gelten. So können bessere Strategien entdeckt werden.","tutorial.exploration.exploit":"Exploitation bedeutet, das zu nutzen, was das Modell momentan für die beste Aktion hält.","tutorial.exploration.epsilon":"Epsilon bestimmt, wie oft das DQN zufällig erkundet. Meist startet es hoch und sinkt während des Trainings.",
"tutorial.experiment.question":"Starte mit einer klaren Frage, zum Beispiel: Hilft ein langsamerer Epsilon-Abfall beim Holzschwert-Ziel?","tutorial.experiment.change_one":"Ändere eine wichtige Variable und lasse den Rest des Versuchs gleich.","tutorial.experiment.compare":"Trainiere beide Einstellungen lange genug und vergleiche Erfolgsrate, Belohnung und Stabilität.","tutorial.experiment.conclusion":"Notiere, was passiert ist und ob die Daten deine ursprüngliche Idee unterstützen.","tutorial.wait_action":"Führe die hervorgehobene Aktion in MinecraftRLLab aus, um weiterzumachen.",
})
STRINGS.update({
"dashboard.current_run":"aktueller Lauf","dashboard.episode_total":"Episodensumme","dashboard.exploration":"Erkundung","dashboard.latest_update":"letztes Update","dashboard.session":"Sitzung",
"error.connect_first":"Verbinde zuerst den Minecraft-Server.","error.plugin_missing":"Im Ordner server-plugin/ wurde kein mitgeliefertes Plugin-JAR gefunden.","error.stop_training_manual":"Stoppe das Training vor einem manuellen Schritt.","error.action_unavailable":"Die ausgewählte Aktion wird vom Server nicht angeboten.","error.no_model":"Noch kein DQN-Modell vorhanden. Starte ein Training oder lade einen Checkpoint.","error.connect_action_space":"Verbinde zuerst den Server, damit die Größe des Aktionsraums bekannt ist.","models.saved":"Checkpoint gespeichert: {path}","models.loaded":"Checkpoint geladen: {path}","updates.checking":"Prüfen…","updates.no_build":"Kein Build gefunden",
})
