STRINGS = {
"app.name":"MinecraftRLLab","app.tagline":"Teach an agent to survive, build and explore in Minecraft.","app.restart_required":"Reopen the app to apply language or experience-mode changes.",
"common.continue":"Continue","common.back":"Back","common.cancel":"Cancel","common.save":"Save","common.close":"Close","common.start":"Start","common.stop":"Stop","common.next":"Next","common.done":"Done",
"nav.dashboard":"Dashboard","nav.server":"Minecraft Server","nav.goals":"Goals","nav.manual":"Manual Actions","nav.observations":"Observations","nav.history":"History","nav.models":"Models","nav.updates":"Updates","nav.settings":"Settings","nav.learning":"Learn",
"onboarding.title":"Welcome to MinecraftRLLab","onboarding.subtitle":"Choose how you want to explore reinforcement learning.","onboarding.language":"Language","onboarding.mode":"Experience","onboarding.name":"What should we call you?","onboarding.finish":"Start exploring",
"mode.kids.title":"Kids / First Steps","mode.kids.description":"A playful interface with big missions, stars and guided lessons.","mode.beginner.title":"Beginner","mode.beginner.description":"The full app with friendly explanations and tutorials.","mode.research.title":"Research","mode.research.description":"Live metrics, models and experiment controls.","mode.advanced.title":"Advanced","mode.advanced.description":"Research mode plus raw observations and debugging tools.",
"kids.home":"Home","kids.missions":"Missions","kids.learn":"Learn","kids.progress":"My Progress","kids.server":"Server","kids.hello":"Hi {name}! 👋","kids.ready":"Ready to teach your Minecraft agent?","kids.pick_mission":"Pick a mission","kids.big_start":"▶ Teach the agent","kids.big_stop":"■ Stop training",
"kids.connected":"Minecraft is connected!","kids.not_connected":"Connect Minecraft first","kids.reward":"Reward","kids.stars":"Stars","kids.episode":"Episode {number}","kids.demo_badge":"DEMO","kids.demo_start":"Try a demo lesson","kids.real_start":"Train in Minecraft","kids.tip":"Tip: the agent learns by trying things and collecting rewards.",
"goal.diamond.title":"Find a diamond","goal.diamond.description":"Mine and obtain a real diamond.","goal.portal.title":"Build a Nether portal","goal.portal.description":"Construct and activate a portal.","goal.sword.title":"Craft a wooden sword","goal.sword.description":"Gather wood and craft the sword.","goal.zombie.title":"Defeat a zombie","goal.zombie.description":"Find and defeat a zombie.",
"kids.goal.diamond.title":"Find a shiny diamond 💎","kids.goal.diamond.description":"Can your agent explore underground and bring back a diamond?","kids.goal.portal.title":"Open a purple portal 🟪","kids.goal.portal.description":"Help the agent build a working doorway to the Nether.","kids.goal.sword.title":"Make a wooden sword 🗡️","kids.goal.sword.description":"Start with wood and learn the steps to craft a sword.","kids.goal.zombie.title":"Beat a zombie 🧟","kids.goal.zombie.description":"Teach the agent to find a zombie and win the fight.",
"learning.title":"Learning Hub","learning.subtitle":"Interactive lessons that explain what the agent is doing.","learning.completed":"Completed","learning.steps":"{done}/{total} steps","learning.try_demo":"Try in demo mode","learning.glossary":"RL Glossary","learning.achievements":"Achievements","learning.experiments":"Experiment Lab",
"tutorial.agent.title":"What is an agent?","tutorial.agent.description":"Meet the learner that chooses actions in Minecraft.","tutorial.rewards.title":"Goals & rewards","tutorial.rewards.description":"See how points tell the agent what helped.","tutorial.first_training.title":"Your first training run","tutorial.first_training.description":"Connect Minecraft, choose a goal and run one episode.","tutorial.graph.title":"Read the reward graph","tutorial.graph.description":"Learn what rising and falling rewards can mean.","tutorial.exploration.title":"Exploration vs. exploitation","tutorial.exploration.description":"Why epsilon makes the agent sometimes try something new.","tutorial.experiment.title":"Your first experiment","tutorial.experiment.description":"Compare two training settings like a researcher.",
"tutorial.step.choose_goal":"Choose the Wooden Sword mission.","tutorial.step.connect":"Connect the app to your Paper server.","tutorial.step.start":"Start one training episode.","tutorial.step.watch_reward":"Watch the agent receive at least one reward.","tutorial.step.finish_episode":"Finish the episode and inspect the result.",
"glossary.agent.term":"Agent","glossary.agent.explanation":"The decision maker that observes Minecraft and chooses actions.","glossary.agent.kids":"The little Minecraft learner you are teaching.","glossary.reward.term":"Reward","glossary.reward.explanation":"A numeric signal that tells the agent whether an outcome was useful.","glossary.reward.kids":"Points that say: that helped! or try something else!","glossary.epsilon.term":"Epsilon","glossary.epsilon.explanation":"The probability that the agent explores with a random action instead of choosing its current best action.","glossary.epsilon.kids":"A curiosity knob: how often should I try something new?","glossary.episode.term":"Episode","glossary.episode.explanation":"One training attempt from reset until success, failure or timeout.","glossary.episode.kids":"One complete try at the mission.",
"achievement.first_tutorial":"First Steps","achievement.first_episode":"First Episode","achievement.first_success":"It Learned!","achievement.diamond_mind":"Diamond Mind","achievement.portal_master":"Portal Master","achievement.zombie_hunter":"Zombie Hunter","achievement.model_keeper":"Model Keeper","achievement.scientist":"Young Scientist",
"settings.language":"Language","settings.experience_mode":"Experience mode","settings.kid_name":"Display name","settings.update_channel":"Default update channel","settings.auto_updates":"Check for updates when the app starts","settings.repository":"GitHub repository","settings.saved":"Settings saved",
"server.title":"Minecraft Server","server.host":"Host","server.port":"Port","server.player":"Player","server.token":"Token","server.connect":"Connect","server.install_plugin":"Install / Update Plugin","server.choose_folder":"Paper server folder","server.plugin_installed":"Plugin installed: {path}",
"status.connected":"Connected","status.connecting":"Connecting…","status.error":"Error","status.training":"Training","status.idle":"Idle",
"research.dashboard.title":"Training Dashboard","research.dashboard.subtitle":"Live reinforcement-learning telemetry from Minecraft","research.goals.title":"Training Goal","research.goals.subtitle":"Choose the task and curriculum profile","research.learning.title":"Learning Hub","research.learning.subtitle":"Tutorials, glossary and experiments without hiding the research tools.",
}
STRINGS.update({
"connection.subtitle":"Connect, bind a player, or install the bundled Paper plugin","connection.server_setup":"SERVER SETUP","connection.browse":"Browse","connection.install_hint":"The bundled plugin will be copied into the server's plugins/ folder.","connection.disconnected":"Disconnected",
"dashboard.episode":"Episode","dashboard.reward":"Reward","dashboard.epsilon":"Epsilon","dashboard.loss":"Loss","dashboard.success_rate":"Success rate","dashboard.best_reward":"Best reward","dashboard.chart":"EPISODE REWARD","dashboard.episodes":"Episodes","dashboard.offset":"Offset","dashboard.last_action":"Action: {action}","dashboard.start":"▶  Start training","dashboard.stop":"■  Stop",
"goals.profile":"Profile","goals.curriculum_note":"CURRICULUM supplies goal-specific starter items to validate learning faster. Success is still checked from real Minecraft state.",
"manual.title":"Manual Environment Control","manual.subtitle":"Inspect the action space before or between training runs","manual.action":"ACTION","manual.execute":"Execute one step","manual.connect_hint":"Connect to a server to load the action space.","manual.actions_count":"{count} actions advertised by the plugin.",
"observation.title":"Observation Inspector","observation.subtitle":"Raw environment state received from the Paper plugin","observation.position":"Position","observation.health":"Health","observation.food":"Food","observation.dimension":"Dimension","observation.zombies":"Nearby zombies","observation.target":"Target",
"history.title":"Episode History","history.subtitle":"Completed episodes from this session","history.episode":"Episode","history.steps":"Steps","history.reward":"Reward","history.success":"Success","history.reason":"Reason","history.yes":"YES","history.no":"NO",
"models.title":"Model Checkpoints","models.subtitle":"Save and restore PyTorch DQN checkpoints","models.none":"No model loaded yet.","models.save":"Save checkpoint","models.load":"Load checkpoint",
"updates.title":"Builds & Updates","updates.subtitle":"Verified releases and freshly built Nightlies from GitHub","updates.channel":"Channel","updates.check":"Check GitHub","updates.not_checked":"Not checked","updates.placeholder":"Build information will appear here.",
})
STRINGS.update({
"tutorial.agent.observe":"First the agent receives an observation: health, inventory, nearby blocks, targets and other Minecraft state.","tutorial.agent.action":"Then it chooses one action, such as moving, looking, mining, crafting or attacking.","tutorial.agent.learn":"After seeing the reward and the next observation, the learning algorithm can make useful actions more likely in the future.",
"tutorial.rewards.points":"Rewards are numbers. Positive rewards encourage progress; the final goal gets the strongest positive signal.","tutorial.rewards.negative":"Small negative rewards can discourage wasted steps, damage or actions that move away from the goal.","tutorial.rewards.shaping":"Reward shaping adds intermediate hints. It should guide learning without pretending the real goal was completed.",
"tutorial.graph.trend":"A rising average reward can mean the policy is improving, but one lucky episode is not enough evidence.","tutorial.graph.noise":"RL curves are noisy because Minecraft situations and exploratory actions vary between episodes.","tutorial.graph.compare":"Compare many episodes or repeated runs instead of judging one point on the graph.",
"tutorial.exploration.explore":"Exploration means trying actions that are not currently considered best. This can discover better strategies.","tutorial.exploration.exploit":"Exploitation means using what the model currently believes is the best action.","tutorial.exploration.epsilon":"Epsilon controls how often the DQN explores randomly. It usually starts high and decreases as training continues.",
"tutorial.experiment.question":"Start with one clear question, for example: does a slower epsilon decay improve the Wooden Sword task?","tutorial.experiment.change_one":"Change one important variable while keeping the rest of the setup the same.","tutorial.experiment.compare":"Run enough episodes for both settings and compare success rate, reward and training stability.","tutorial.experiment.conclusion":"Write down what happened and whether the evidence supports your original idea.","tutorial.wait_action":"Do the highlighted action in MinecraftRLLab to continue.",
})
STRINGS.update({
"dashboard.current_run":"current run","dashboard.episode_total":"episode total","dashboard.exploration":"exploration","dashboard.latest_update":"latest update","dashboard.session":"session",
"error.connect_first":"Connect to the Minecraft server first.","error.plugin_missing":"No bundled plugin JAR was found in server-plugin/.","error.stop_training_manual":"Stop training before manual stepping.","error.action_unavailable":"The selected action is not advertised by the server.","error.no_model":"No DQN model exists yet. Start training or load a checkpoint first.","error.connect_action_space":"Connect to the server first so the action-space size is known.","models.saved":"Saved checkpoint: {path}","models.loaded":"Loaded checkpoint: {path}","updates.checking":"Checking…","updates.no_build":"No build found",
})
