STRINGS = {
"app.name":"MinecraftRLLab","app.tagline":"Enseña a un agente a sobrevivir, construir y explorar en Minecraft.","app.restart_required":"Vuelve a abrir la aplicación para aplicar el idioma o el modo de experiencia.",
"common.continue":"Continuar","common.back":"Atrás","common.cancel":"Cancelar","common.save":"Guardar","common.close":"Cerrar","common.start":"Iniciar","common.stop":"Detener","common.next":"Siguiente","common.done":"Listo",
"nav.dashboard":"Panel","nav.server":"Servidor Minecraft","nav.goals":"Objetivos","nav.manual":"Acciones manuales","nav.observations":"Observaciones","nav.history":"Historial","nav.models":"Modelos","nav.updates":"Actualizaciones","nav.settings":"Ajustes","nav.learning":"Aprender",
"onboarding.title":"Bienvenido a MinecraftRLLab","onboarding.subtitle":"Elige cómo quieres descubrir el aprendizaje por refuerzo.","onboarding.language":"Idioma","onboarding.mode":"Experiencia","onboarding.name":"¿Cómo quieres que te llamemos?","onboarding.finish":"Empezar",
"mode.kids.title":"Niños / Primeros pasos","mode.kids.description":"Una interfaz divertida con grandes misiones, estrellas y lecciones guiadas.","mode.beginner.title":"Principiante","mode.beginner.description":"La aplicación completa con explicaciones sencillas y tutoriales.","mode.research.title":"Investigación","mode.research.description":"Métricas en vivo, modelos y controles de experimentos.","mode.advanced.title":"Avanzado","mode.advanced.description":"Modo investigación más observaciones sin procesar y herramientas de depuración.",
"kids.home":"Inicio","kids.missions":"Misiones","kids.learn":"Aprender","kids.progress":"Mi progreso","kids.server":"Servidor","kids.hello":"¡Hola {name}! 👋","kids.ready":"¿Listo para enseñar a tu agente de Minecraft?","kids.pick_mission":"Elige una misión","kids.big_start":"▶ Entrenar al agente","kids.big_stop":"■ Detener entrenamiento",
"kids.connected":"¡Minecraft está conectado!","kids.not_connected":"Conecta Minecraft primero","kids.reward":"Recompensa","kids.stars":"Estrellas","kids.episode":"Episodio {number}","kids.demo_badge":"DEMO","kids.demo_start":"Probar una lección demo","kids.real_start":"Entrenar en Minecraft","kids.tip":"Consejo: el agente aprende probando cosas y recogiendo recompensas.",
"goal.diamond.title":"Encontrar un diamante","goal.diamond.description":"Minar y obtener un diamante real.","goal.portal.title":"Construir un portal al Nether","goal.portal.description":"Construir y activar un portal.","goal.sword.title":"Fabricar una espada de madera","goal.sword.description":"Recoger madera y fabricar la espada.","goal.zombie.title":"Derrotar un zombi","goal.zombie.description":"Encontrar y derrotar un zombi.",
"kids.goal.diamond.title":"Encuentra un diamante brillante 💎","kids.goal.diamond.description":"¿Puede tu agente explorar bajo tierra y traer un diamante?","kids.goal.portal.title":"Abre un portal morado 🟪","kids.goal.portal.description":"Ayuda al agente a construir una puerta real al Nether.","kids.goal.sword.title":"Haz una espada de madera 🗡️","kids.goal.sword.description":"Empieza con madera y aprende los pasos para fabricar una espada.","kids.goal.zombie.title":"Vence a un zombi 🧟","kids.goal.zombie.description":"Enseña al agente a encontrar un zombi y ganar la pelea.",
"learning.title":"Centro de aprendizaje","learning.subtitle":"Lecciones interactivas explican lo que está haciendo el agente.","learning.completed":"Completado","learning.steps":"{done}/{total} pasos","learning.try_demo":"Probar en modo demo","learning.glossary":"Glosario de RL","learning.achievements":"Logros","learning.experiments":"Laboratorio de experimentos",
"tutorial.agent.title":"¿Qué es un agente?","tutorial.agent.description":"Conoce al aprendiz que elige acciones en Minecraft.","tutorial.rewards.title":"Objetivos y recompensas","tutorial.rewards.description":"Mira cómo los puntos indican al agente qué ayudó.","tutorial.first_training.title":"Tu primer entrenamiento","tutorial.first_training.description":"Conecta Minecraft, elige un objetivo y ejecuta un episodio.","tutorial.graph.title":"Leer el gráfico de recompensas","tutorial.graph.description":"Aprende qué pueden significar las recompensas que suben o bajan.","tutorial.exploration.title":"Exploración vs. explotación","tutorial.exploration.description":"Por qué epsilon hace que el agente pruebe algo nuevo algunas veces.","tutorial.experiment.title":"Tu primer experimento","tutorial.experiment.description":"Compara dos ajustes de entrenamiento como un investigador.",
"tutorial.step.choose_goal":"Elige la misión Espada de madera.","tutorial.step.connect":"Conecta la aplicación a tu servidor Paper.","tutorial.step.start":"Inicia un episodio de entrenamiento.","tutorial.step.watch_reward":"Observa al menos una recompensa del agente.","tutorial.step.finish_episode":"Termina el episodio y revisa el resultado.",
"glossary.agent.term":"Agente","glossary.agent.explanation":"El decisor que observa Minecraft y elige acciones.","glossary.agent.kids":"El pequeño aprendiz de Minecraft al que estás enseñando.","glossary.reward.term":"Recompensa","glossary.reward.explanation":"Una señal numérica que indica al agente si un resultado fue útil.","glossary.reward.kids":"Puntos que dicen: ¡eso ayudó! o ¡prueba otra cosa!","glossary.epsilon.term":"Epsilon","glossary.epsilon.explanation":"La probabilidad de que el agente explore con una acción aleatoria en lugar de elegir su mejor acción actual.","glossary.epsilon.kids":"Un control de curiosidad: ¿con qué frecuencia pruebo algo nuevo?","glossary.episode.term":"Episodio","glossary.episode.explanation":"Un intento de entrenamiento desde el reinicio hasta éxito, fracaso o límite de tiempo.","glossary.episode.kids":"Un intento completo de la misión.",
"achievement.first_tutorial":"Primeros pasos","achievement.first_episode":"Primer episodio","achievement.first_success":"¡Aprendió!","achievement.diamond_mind":"Mente de diamante","achievement.portal_master":"Maestro de portales","achievement.zombie_hunter":"Cazador de zombis","achievement.model_keeper":"Guardián de modelos","achievement.scientist":"Joven científico",
"settings.language":"Idioma","settings.experience_mode":"Modo de experiencia","settings.kid_name":"Nombre mostrado","settings.update_channel":"Canal de actualización predeterminado","settings.auto_updates":"Buscar actualizaciones al iniciar","settings.repository":"Repositorio de GitHub","settings.saved":"Ajustes guardados",
"server.title":"Servidor Minecraft","server.host":"Host","server.port":"Puerto","server.player":"Jugador","server.token":"Token","server.connect":"Conectar","server.install_plugin":"Instalar / actualizar plugin","server.choose_folder":"Carpeta del servidor Paper","server.plugin_installed":"Plugin instalado: {path}",
"status.connected":"Conectado","status.connecting":"Conectando…","status.error":"Error","status.training":"Entrenando","status.idle":"Listo",
"research.dashboard.title":"Panel de entrenamiento","research.dashboard.subtitle":"Telemetría de aprendizaje por refuerzo en vivo desde Minecraft","research.goals.title":"Objetivo de entrenamiento","research.goals.subtitle":"Elige la tarea y el perfil de currículo","research.learning.title":"Centro de aprendizaje","research.learning.subtitle":"Tutoriales, glosario y experimentos junto a las herramientas de investigación.",
}
STRINGS.update({
"connection.subtitle":"Conecta un jugador o instala el plugin de Paper incluido","connection.server_setup":"CONFIGURACIÓN DEL SERVIDOR","connection.browse":"Examinar","connection.install_hint":"El plugin incluido se copiará a la carpeta plugins/ del servidor.","connection.disconnected":"Desconectado",
"dashboard.episode":"Episodio","dashboard.reward":"Recompensa","dashboard.epsilon":"Epsilon","dashboard.loss":"Pérdida","dashboard.success_rate":"Tasa de éxito","dashboard.best_reward":"Mejor recompensa","dashboard.chart":"RECOMPENSA POR EPISODIO","dashboard.episodes":"Episodios","dashboard.offset":"Desplazamiento","dashboard.last_action":"Acción: {action}","dashboard.start":"▶  Iniciar entrenamiento","dashboard.stop":"■  Detener",
"goals.profile":"Perfil","goals.curriculum_note":"CURRICULUM proporciona objetos iniciales según el objetivo para validar el aprendizaje más rápido. El éxito sigue comprobándose con el estado real de Minecraft.",
"manual.title":"Control manual del entorno","manual.subtitle":"Inspecciona el espacio de acciones antes o entre entrenamientos","manual.action":"ACCIÓN","manual.execute":"Ejecutar un paso","manual.connect_hint":"Conecta un servidor para cargar el espacio de acciones.","manual.actions_count":"El plugin anuncia {count} acciones.",
"observation.title":"Inspector de observaciones","observation.subtitle":"Estado bruto recibido del plugin de Paper","observation.position":"Posición","observation.health":"Salud","observation.food":"Comida","observation.dimension":"Dimensión","observation.zombies":"Zombis cercanos","observation.target":"Objetivo",
"history.title":"Historial de episodios","history.subtitle":"Episodios completados en esta sesión","history.episode":"Episodio","history.steps":"Pasos","history.reward":"Recompensa","history.success":"Éxito","history.reason":"Motivo","history.yes":"SÍ","history.no":"NO",
"models.title":"Puntos de control del modelo","models.subtitle":"Guardar y restaurar checkpoints DQN de PyTorch","models.none":"Todavía no hay un modelo cargado.","models.save":"Guardar checkpoint","models.load":"Cargar checkpoint",
"updates.title":"Builds y actualizaciones","updates.subtitle":"Versiones verificadas y Nightlies recién construidas desde GitHub","updates.channel":"Canal","updates.check":"Comprobar GitHub","updates.not_checked":"Sin comprobar","updates.placeholder":"La información del build aparecerá aquí.",
})
STRINGS.update({
"tutorial.agent.observe":"Primero el agente recibe una observación: salud, inventario, bloques cercanos, objetivos y más estado de Minecraft.","tutorial.agent.action":"Después elige una acción, como moverse, mirar, minar, fabricar o atacar.","tutorial.agent.learn":"Tras ver la recompensa y la siguiente observación, el algoritmo puede hacer más probables las acciones útiles en el futuro.",
"tutorial.rewards.points":"Las recompensas son números. Los valores positivos fomentan el progreso y el objetivo real recibe la señal positiva más fuerte.","tutorial.rewards.negative":"Pequeñas recompensas negativas pueden desalentar pasos desperdiciados, daño o acciones que alejan del objetivo.","tutorial.rewards.shaping":"Reward shaping añade pistas intermedias sin fingir que el objetivo real ya se completó.",
"tutorial.graph.trend":"Una recompensa media creciente puede indicar una mejor estrategia, pero un episodio afortunado no es suficiente evidencia.","tutorial.graph.noise":"Las curvas de RL tienen ruido porque las situaciones de Minecraft y las acciones de exploración cambian entre episodios.","tutorial.graph.compare":"Compara muchos episodios o varias ejecuciones en lugar de juzgar un único punto del gráfico.",
"tutorial.exploration.explore":"Explorar significa probar acciones que todavía no parecen las mejores para descubrir estrategias nuevas.","tutorial.exploration.exploit":"Explotar significa usar lo que el modelo cree actualmente que es la mejor acción.","tutorial.exploration.epsilon":"Epsilon controla con qué frecuencia el DQN explora aleatoriamente. Suele empezar alto y bajar durante el entrenamiento.",
"tutorial.experiment.question":"Empieza con una pregunta clara, por ejemplo: ¿una reducción más lenta de epsilon ayuda con la espada de madera?","tutorial.experiment.change_one":"Cambia una variable importante y mantén igual el resto del experimento.","tutorial.experiment.compare":"Ejecuta suficientes episodios con ambas configuraciones y compara éxito, recompensa y estabilidad.","tutorial.experiment.conclusion":"Anota qué ocurrió y si los datos apoyan tu idea original.","tutorial.wait_action":"Realiza la acción indicada en MinecraftRLLab para continuar.",
})
STRINGS.update({
"dashboard.current_run":"ejecución actual","dashboard.episode_total":"total del episodio","dashboard.exploration":"exploración","dashboard.latest_update":"última actualización","dashboard.session":"sesión",
"error.connect_first":"Conecta primero el servidor de Minecraft.","error.plugin_missing":"No se encontró el JAR del plugin incluido en server-plugin/.","error.stop_training_manual":"Detén el entrenamiento antes de ejecutar un paso manual.","error.action_unavailable":"El servidor no anuncia la acción seleccionada.","error.no_model":"Todavía no existe un modelo DQN. Inicia un entrenamiento o carga un checkpoint.","error.connect_action_space":"Conecta primero el servidor para conocer el tamaño del espacio de acciones.","models.saved":"Checkpoint guardado: {path}","models.loaded":"Checkpoint cargado: {path}","updates.checking":"Comprobando…","updates.no_build":"No se encontró ningún build",
})
