STRINGS = {
"app.name":"MinecraftRLLab","app.tagline":"Apprends à un agent à survivre, construire et explorer dans Minecraft.","app.restart_required":"Rouvre l’application pour appliquer la langue ou le mode d’expérience.",
"common.continue":"Continuer","common.back":"Retour","common.cancel":"Annuler","common.save":"Enregistrer","common.close":"Fermer","common.start":"Démarrer","common.stop":"Arrêter","common.next":"Suivant","common.done":"Terminé",
"nav.dashboard":"Tableau de bord","nav.server":"Serveur Minecraft","nav.goals":"Objectifs","nav.manual":"Actions manuelles","nav.observations":"Observations","nav.history":"Historique","nav.models":"Modèles","nav.updates":"Mises à jour","nav.settings":"Paramètres","nav.learning":"Apprendre",
"onboarding.title":"Bienvenue dans MinecraftRLLab","onboarding.subtitle":"Choisis comment tu veux découvrir l’apprentissage par renforcement.","onboarding.language":"Langue","onboarding.mode":"Expérience","onboarding.name":"Comment doit-on t’appeler ?","onboarding.finish":"Commencer",
"mode.kids.title":"Enfants / Premiers pas","mode.kids.description":"Une interface ludique avec grandes missions, étoiles et leçons guidées.","mode.beginner.title":"Débutant","mode.beginner.description":"L’application complète avec des explications simples et des tutoriels.","mode.research.title":"Recherche","mode.research.description":"Mesures en direct, modèles et commandes d’expériences.","mode.advanced.title":"Avancé","mode.advanced.description":"Mode recherche avec observations brutes et outils de débogage.",
"kids.home":"Accueil","kids.missions":"Missions","kids.learn":"Apprendre","kids.progress":"Mes progrès","kids.server":"Serveur","kids.hello":"Salut {name} ! 👋","kids.ready":"Prêt à apprendre des choses à ton agent Minecraft ?","kids.pick_mission":"Choisis une mission","kids.big_start":"▶ Entraîner l’agent","kids.big_stop":"■ Arrêter l’entraînement",
"kids.connected":"Minecraft est connecté !","kids.not_connected":"Connecte d’abord Minecraft","kids.reward":"Récompense","kids.stars":"Étoiles","kids.episode":"Épisode {number}","kids.demo_badge":"DÉMO","kids.demo_start":"Essayer une leçon démo","kids.real_start":"Entraîner dans Minecraft","kids.tip":"Astuce : l’agent apprend en essayant des choses et en gagnant des récompenses.",
"goal.diamond.title":"Trouver un diamant","goal.diamond.description":"Miner et obtenir un vrai diamant.","goal.portal.title":"Construire un portail du Nether","goal.portal.description":"Construire et activer un portail.","goal.sword.title":"Fabriquer une épée en bois","goal.sword.description":"Ramasser du bois et fabriquer l’épée.","goal.zombie.title":"Vaincre un zombie","goal.zombie.description":"Trouver et vaincre un zombie.",
"kids.goal.diamond.title":"Trouve un diamant brillant 💎","kids.goal.diamond.description":"Ton agent peut-il explorer sous terre et rapporter un diamant ?","kids.goal.portal.title":"Ouvre un portail violet 🟪","kids.goal.portal.description":"Aide l’agent à construire une vraie porte vers le Nether.","kids.goal.sword.title":"Fabrique une épée en bois 🗡️","kids.goal.sword.description":"Commence avec du bois et apprends les étapes pour créer une épée.","kids.goal.zombie.title":"Bats un zombie 🧟","kids.goal.zombie.description":"Apprends à l’agent à trouver un zombie et gagner le combat.",
"learning.title":"Centre d’apprentissage","learning.subtitle":"Des leçons interactives expliquent ce que fait l’agent.","learning.completed":"Terminé","learning.steps":"{done}/{total} étapes","learning.try_demo":"Essayer en mode démo","learning.glossary":"Glossaire RL","learning.achievements":"Succès","learning.experiments":"Laboratoire d’expériences",
"tutorial.agent.title":"Qu’est-ce qu’un agent ?","tutorial.agent.description":"Découvre l’apprenant qui choisit des actions dans Minecraft.","tutorial.rewards.title":"Objectifs et récompenses","tutorial.rewards.description":"Découvre comment les points indiquent ce qui aide l’agent.","tutorial.first_training.title":"Ton premier entraînement","tutorial.first_training.description":"Connecte Minecraft, choisis un objectif et lance un épisode.","tutorial.graph.title":"Lire le graphe des récompenses","tutorial.graph.description":"Comprends ce que peuvent signifier les récompenses qui montent ou descendent.","tutorial.exploration.title":"Exploration ou exploitation","tutorial.exploration.description":"Pourquoi epsilon pousse parfois l’agent à essayer quelque chose de nouveau.","tutorial.experiment.title":"Ta première expérience","tutorial.experiment.description":"Compare deux réglages d’entraînement comme un chercheur.",
"tutorial.step.choose_goal":"Choisis la mission Épée en bois.","tutorial.step.connect":"Connecte l’application à ton serveur Paper.","tutorial.step.start":"Lance un épisode d’entraînement.","tutorial.step.watch_reward":"Observe au moins une récompense de l’agent.","tutorial.step.finish_episode":"Termine l’épisode et regarde le résultat.",
"glossary.agent.term":"Agent","glossary.agent.explanation":"Le décideur qui observe Minecraft et choisit des actions.","glossary.agent.kids":"Le petit élève Minecraft auquel tu apprends des choses.","glossary.reward.term":"Récompense","glossary.reward.explanation":"Un signal numérique qui indique à l’agent si un résultat était utile.","glossary.reward.kids":"Des points qui disent : ça aide ! ou essaie autre chose !","glossary.epsilon.term":"Epsilon","glossary.epsilon.explanation":"La probabilité que l’agent explore avec une action aléatoire au lieu de choisir sa meilleure action actuelle.","glossary.epsilon.kids":"Un bouton de curiosité : à quelle fréquence essayer quelque chose de nouveau ?","glossary.episode.term":"Épisode","glossary.episode.explanation":"Une tentative d’entraînement du reset jusqu’au succès, à l’échec ou au temps limite.","glossary.episode.kids":"Une tentative complète de la mission.",
"achievement.first_tutorial":"Premiers pas","achievement.first_episode":"Premier épisode","achievement.first_success":"Il a appris !","achievement.diamond_mind":"Esprit diamant","achievement.portal_master":"Maître des portails","achievement.zombie_hunter":"Chasseur de zombies","achievement.model_keeper":"Gardien des modèles","achievement.scientist":"Jeune scientifique",
"settings.language":"Langue","settings.experience_mode":"Mode d’expérience","settings.kid_name":"Nom affiché","settings.update_channel":"Canal de mise à jour par défaut","settings.auto_updates":"Rechercher les mises à jour au démarrage","settings.repository":"Dépôt GitHub","settings.saved":"Paramètres enregistrés",
"server.title":"Serveur Minecraft","server.host":"Hôte","server.port":"Port","server.player":"Joueur","server.token":"Jeton","server.connect":"Connexion","server.install_plugin":"Installer / mettre à jour le plugin","server.choose_folder":"Dossier du serveur Paper","server.plugin_installed":"Plugin installé : {path}",
"status.connected":"Connecté","status.connecting":"Connexion…","status.error":"Erreur","status.training":"Entraînement","status.idle":"Prêt",
"research.dashboard.title":"Tableau d’entraînement","research.dashboard.subtitle":"Télémétrie d’apprentissage par renforcement en direct depuis Minecraft","research.goals.title":"Objectif d’entraînement","research.goals.subtitle":"Choisis la tâche et le profil de curriculum","research.learning.title":"Centre d’apprentissage","research.learning.subtitle":"Tutoriels, glossaire et expériences avec les outils de recherche.",
}
STRINGS.update({
"connection.subtitle":"Connecte un joueur ou installe le plugin Paper inclus","connection.server_setup":"CONFIGURATION DU SERVEUR","connection.browse":"Parcourir","connection.install_hint":"Le plugin inclus sera copié dans le dossier plugins/ du serveur.","connection.disconnected":"Déconnecté",
"dashboard.episode":"Épisode","dashboard.reward":"Récompense","dashboard.epsilon":"Epsilon","dashboard.loss":"Perte","dashboard.success_rate":"Taux de réussite","dashboard.best_reward":"Meilleure récompense","dashboard.chart":"RÉCOMPENSE PAR ÉPISODE","dashboard.episodes":"Épisodes","dashboard.offset":"Décalage","dashboard.last_action":"Action : {action}","dashboard.start":"▶  Démarrer l’entraînement","dashboard.stop":"■  Arrêter",
"goals.profile":"Profil","goals.curriculum_note":"CURRICULUM fournit des objets de départ selon l’objectif pour valider l’apprentissage plus vite. Le succès est toujours vérifié avec l’état réel de Minecraft.",
"manual.title":"Contrôle manuel de l’environnement","manual.subtitle":"Examine l’espace d’actions avant ou entre les entraînements","manual.action":"ACTION","manual.execute":"Exécuter une étape","manual.connect_hint":"Connecte un serveur pour charger l’espace d’actions.","manual.actions_count":"{count} actions annoncées par le plugin.",
"observation.title":"Inspecteur d’observations","observation.subtitle":"État brut reçu depuis le plugin Paper","observation.position":"Position","observation.health":"Vie","observation.food":"Faim","observation.dimension":"Dimension","observation.zombies":"Zombies proches","observation.target":"Cible",
"history.title":"Historique des épisodes","history.subtitle":"Épisodes terminés pendant cette session","history.episode":"Épisode","history.steps":"Étapes","history.reward":"Récompense","history.success":"Succès","history.reason":"Raison","history.yes":"OUI","history.no":"NON",
"models.title":"Points de contrôle du modèle","models.subtitle":"Enregistrer et restaurer des checkpoints DQN PyTorch","models.none":"Aucun modèle chargé.","models.save":"Enregistrer le checkpoint","models.load":"Charger le checkpoint",
"updates.title":"Builds et mises à jour","updates.subtitle":"Versions vérifiées et Nightlies fraîchement construites sur GitHub","updates.channel":"Canal","updates.check":"Vérifier GitHub","updates.not_checked":"Non vérifié","updates.placeholder":"Les informations du build apparaîtront ici.",
})
STRINGS.update({
"tutorial.agent.observe":"L’agent reçoit d’abord une observation : vie, inventaire, blocs proches, cibles et autres informations de Minecraft.","tutorial.agent.action":"Ensuite il choisit une action, comme avancer, regarder, miner, fabriquer ou attaquer.","tutorial.agent.learn":"Après la récompense et l’observation suivante, l’algorithme peut rendre les actions utiles plus probables à l’avenir.",
"tutorial.rewards.points":"Les récompenses sont des nombres. Les valeurs positives encouragent le progrès et le vrai objectif reçoit le signal le plus fort.","tutorial.rewards.negative":"De petites récompenses négatives peuvent décourager les étapes inutiles, les dégâts ou les actions qui éloignent du but.","tutorial.rewards.shaping":"Le reward shaping ajoute des indices intermédiaires sans prétendre que le véritable objectif est déjà atteint.",
"tutorial.graph.trend":"Une récompense moyenne qui monte peut indiquer une meilleure stratégie, mais un épisode chanceux ne suffit pas.","tutorial.graph.noise":"Les courbes RL sont bruitées car les situations Minecraft et les actions d’exploration changent entre les épisodes.","tutorial.graph.compare":"Compare de nombreux épisodes ou plusieurs entraînements plutôt qu’un seul point du graphe.",
"tutorial.exploration.explore":"Explorer signifie essayer des actions qui ne semblent pas encore être les meilleures afin de découvrir de nouvelles stratégies.","tutorial.exploration.exploit":"Exploiter signifie utiliser ce que le modèle considère actuellement comme sa meilleure action.","tutorial.exploration.epsilon":"Epsilon contrôle la fréquence d’exploration aléatoire du DQN. Il commence souvent haut puis diminue.",
"tutorial.experiment.question":"Commence par une question claire, par exemple : une décroissance plus lente d’epsilon aide-t-elle pour l’épée en bois ?","tutorial.experiment.change_one":"Modifie une variable importante et garde le reste de l’expérience identique.","tutorial.experiment.compare":"Exécute assez d’épisodes pour les deux réglages et compare réussite, récompense et stabilité.","tutorial.experiment.conclusion":"Note ce qui s’est passé et si les résultats soutiennent ton idée de départ.","tutorial.wait_action":"Effectue l’action indiquée dans MinecraftRLLab pour continuer.",
})
STRINGS.update({
"dashboard.current_run":"exécution actuelle","dashboard.episode_total":"total de l’épisode","dashboard.exploration":"exploration","dashboard.latest_update":"dernière mise à jour","dashboard.session":"session",
"error.connect_first":"Connecte d’abord le serveur Minecraft.","error.plugin_missing":"Aucun plugin JAR inclus n’a été trouvé dans server-plugin/.","error.stop_training_manual":"Arrête l’entraînement avant une étape manuelle.","error.action_unavailable":"L’action sélectionnée n’est pas annoncée par le serveur.","error.no_model":"Aucun modèle DQN n’existe encore. Démarre un entraînement ou charge un checkpoint.","error.connect_action_space":"Connecte d’abord le serveur pour connaître la taille de l’espace d’actions.","models.saved":"Checkpoint enregistré : {path}","models.loaded":"Checkpoint chargé : {path}","updates.checking":"Vérification…","updates.no_build":"Aucun build trouvé",
})
